### ISSUE TITLE
A TwoWay or OneWayToSource binding cannot work on the read-only property 'CurrentPosition'

### ISSUE THREAD

**Issue by dmitrybv** [AlexNek/BindingNavigatorWpf#1]
Hello

When I try to use BindingNavigatorUc it raise error at run time and design time.

System.InvalidOperationException
  HResult=0x80131509
  Message=A TwoWay or OneWayToSource binding cannot work on the read-only property 'CurrentPosition' of type 'System.Windows.Data.BindingListCollectionView'.

```
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:EhLibTestApp.DataSets"
        xmlns:WPF="clr-namespace:EhLib.WPF;assembly=EhLib.WPF"
        xmlns:localBn="clr-namespace:BindingNavigator.View"
        x:Class="EhLibTestApp.WindowDataGrid1"
        mc:Ignorable="d"
        Title="Window DataGrid"
        Height="253"
        Width="689"
        Loaded="Window_Loaded">
  <Window.Resources>
    <local:NorthwindDataSet x:Key="northwindDataSet" />
    <CollectionViewSource x:Key="customersViewSource"
                          Source="{Binding Customers, Source={StaticResource northwindDataSet}}"
                          />
  </Window.Resources>
  <Grid
        DataContext="{StaticResource customersViewSource}"
        >
    <Grid.RowDefinitions>
      <RowDefinition Height="62" />
      <RowDefinition Height="Auto" />
      <RowDefinition Height="*" />
    </Grid.RowDefinitions>

    <localBn:BindingNavigatorUc 
       Grid.Row="1">
    </localBn:BindingNavigatorUc>
    
    <DataGrid x:Name="MainDataGrid"
              ItemsSource="{Binding}"
              AutoGenerateColumns="True"
              EnableRowVirtualization="True"
              Grid.Row="2"
              RowDetailsVisibilityMode="VisibleWhenSelected"
              LoadingRow="MainDataGrid_LoadingRow">
      <DataGrid.Columns>
      </DataGrid.Columns>
    </DataGrid>

  </Grid>
</Window>

```

**Comment by AlexNek** [comment]
Hello Dmitry, thanks for the feedback.
Are you sure that is  XAML which produce the error? As I can't find using CurrentPosition and BindingListCollectionView. In other case I'll try to reproduce the error later. It would be nice if you can attach a sample project.
Thanks Alex

**Comment by AlexNek** [comment]
With the test project I can reproduce your error but the problem is in the way how you use the data source.

Try to use MVVM pattern:
[WPF/MVVM Quick Start Tutorial](https://www.codeproject.com/Articles/165368/WPF-MVVM-Quick-Start-Tutorial)
[Using WPF MVVM for Database Access](https://www.codeproject.com/Articles/124160/Using-WPF-MVVM-for-Database-Access)

I can't see a way to change something in my control now. CurrentPosition is readonly property 
```
System.InvalidOperationException
  HResult=0x80131509
  Message=A TwoWay or OneWayToSource binding cannot work on the read-only property 'CurrentPosition' of type 'System.Windows.Data.BindingListCollectionView'.
  Source=PresentationFramework
  StackTrace:
   at MS.Internal.Data.PropertyPathWorker.CheckReadOnly(Object item, Object info)
   at MS.Internal.Data.PropertyPathWorker.ReplaceItem(Int32 k, Object newO, Object parent)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.AttachDataItem()
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at MS.Internal.Data.DataBindEngine.OnLayoutUpdated(Object sender, EventArgs e)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.UIElement.UpdateLayout()
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at DmitryTest1.App.Main()
```

**Comment by AlexNek** [comment]
I can explain what is happens in your project now.

- You use CollectionViewSource as data source and data context simultaneously.
- You place BindingNavigator in your DataContext
-  BindingNavigator used text box for position control 
```
<TextBox Width="50" Margin="0,0,5,0"  Text="{Binding CurrentPosition, ...}"/>
```
- System try to bind CurrentPosition to your DataContext. But this property is read only
[CollectionView.CurrentPosition Property](https://docs.microsoft.com/en-us/dotnet/api/system.windows.data.collectionview.currentposition?view=netcore-3.1#System_Windows_Data_CollectionView_CurrentPosition)

That why the error produced.

**How to resolve it?**

- As I tell you start to use MVVM Patern and never mix data source with data context.
- Read [usage documentation](https://github.com/AlexNek/BindingNavigatorWpf/blob/develop/docs/usage.md)
The important part is to define binding navigator data context
```
 <View:BindingNavigatorUc DataContext="{Binding BindingNavigatorDataContext}"/>
```
I hope, your problem is solved now. If not write your comment this week, please.
